apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-servicemonitor
  namespace: hello
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: hello
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
