apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
      - name: translator
        image: localhost:5000/translator:0.1
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
